In [10]:
import pandas as pd
import yfinance as yf
from matplotlib import pyplot as plt
from gdeltdoc import GdeltDoc, Filters, near, repeat
from tqdm import tqdm as tq
import json
import json
import urllib

In [11]:
num_features = 10
start_date = "2017-01-01"
end_date = "2020-12-31"

In [25]:
f = open('stock-news/additional/stocks.json','r')
company_list = json.load(f)  
f.close()
company_list = company_list[:500]

/kernel/lib/python3.7/site-packages/ml_kernel/kernel.py:619: UserWarning: The following variables cannot be serialized: f
  warnings.warn(message)

In [26]:
def get_stocks(name_stock):
    #Дергаем акции 
    df_stock_raw = yf.download(name_stock, start=start_date, end=end_date);
    df_stock = df_stock_raw.groupby(pd.Grouper(level="Date", freq="1D")).mean(); 
    #Добовляем процент роста
    df_stock['per_of_growth'] = (df_stock["Close"]-df_stock["Open"])/df_stock["Open"] *100
    return df_stock

In [27]:
def get_features(query):
    api_key = 'AIzaSyD1lvw5a7S2eWHmCHoDNhzl8a0t0hmnF5w'
    service_url = 'https://kgsearch.googleapis.com/v1/entities:search'
    params = {
        'query': query,
        'limit': num_features,
        'indent': True,
        'key': api_key,
    }
    url = service_url + '?' + urllib.parse.urlencode(params)
    response = json.loads(urllib.request.urlopen(url).read())
    features = []
    for element in response['itemListElement']:
        features.append(element['result']['name'].lower())
    return features

In [28]:
def GDELT_request(features):
    all_tone =[]
    all_count_news=[]
    for ft in tq(features):
        f = Filters(
            start_date = start_date,
            end_date = end_date,
            keyword = ft,
        )
        gd = GdeltDoc()
        timelinetone_raw= gd.timeline_search("timelinetone", f)
        #Убираю UTC
        timelinetone_raw['datetime']=timelinetone_raw.datetime.astype('datetime64[ns]')
        #Индексирую по datetime
        timelinetone = timelinetone_raw.set_index(['datetime'])
        #Меняю название колонки как у  features
        #Решил сделать одно название у всех было -                ft +"_av_tone"
        timelinetone=timelinetone.rename(columns={'Average Tone': "Mid_tone"})
        all_tone.append(timelinetone)

        #Тоже самое делаю для количества новостей
        timelinevolraw = gd.timeline_search("timelinevolraw", f)
        timelinevolraw['datetime']=timelinevolraw.datetime.astype('datetime64[ns]')
        timelinevolraw = timelinevolraw.set_index(['datetime'])
        #Решил сделать одно название у всех было -                        ft +"_art_count"
        timelinevolraw = timelinevolraw.rename(columns={'Article Count': "Sum_count"})
        all_count_news.append(timelinevolraw.drop(['All Articles'],axis=1))
        
    #Считаю среднее по тону новостей all_tone это отдельные датафрейимы
    #если название колонок одинаковое можно складывать их c помощю - add
    tone=all_tone[0]
    for i in range(1,len(all_tone)):
        tone = tone.add(all_tone[i])
    #средняя тональность для всех новостей    
    tone_midd = tone / len(all_tone)
    
    
    count_news=all_count_news[0]
    #Считаю суммарное количество новостей
    for i in range(1,len(all_count_news)):
        count_news = count_news.add(all_count_news[i])
    
    return tone_midd, count_news

In [ ]:
full_dataset = pd.DataFrame()
for company in tq(company_list):
    name_stock = company["ticket"]
    name_for_features = company["name"]
    try:
        #Дергаю акции 
        df_stock = get_stocks(name_stock)
        #Дергаю из графа слова
        #!Добавить само название компании в начало
        features = get_features(name_for_features)
        #Делаю запрос к Gdelt
        tone_midd, count_news = GDELT_request(features)

        #Стакаем тональность и количество новостей
        df_stock = pd.merge(df_stock,tone_midd, left_index=True,right_index=True)
        df_stock = pd.merge(df_stock,count_news, left_index=True,right_index=True)

        full_dataset = full_dataset.append(df_stock)
    except:
        print("Something fuck up with "+str(name_for_features))
        
full_dataset.to_csv("out.csv")

In [24]:
full_dataset

,Open,High,Low,Close,Adj Close,Volume,per_of_growth,Mid_tone,Sum_count
2017-01-03,38.630001,39.080002,38.340000,39.049999,36.148453,9677300.0,1.087233,-0.180050,106
2017-01-04,39.060001,39.730000,39.060001,39.360001,36.435421,22644500.0,0.768047,-0.840975,122
2017-01-05,39.240002,39.750000,38.980000,39.700001,36.750153,12080100.0,1.172271,-0.881550,119
2017-01-06,39.700001,40.990002,39.660000,40.779999,37.749912,14628900.0,2.720398,-0.618025,151
2017-01-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.046625,52
...,...,...,...,...,...,...,...,...,...
2020-12-26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0
2020-12-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0
2020-12-28,23.480000,23.610001,23.240000,23.299999,23.146763,3892600.0,-0.766611,0.000000,0
2020-12-29,23.379999,23.620001,23.080000,23.309999,23.156698,2818800.0,-0.299400,0.273900,9
2020-12-30,22.980000,23.120001,22.660000,22.780001,22.630184,8226300.0,-0.870317,2.821950,21